### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gregtampa** [kevinohashi/php-riot-api#33]
// The summoner we are looking for. Lowercase is recommended.
$SUMMONER_NAME = 'Øhm';

example will break with this name...
just saying... need to fix your urlencode

**Comment by markkuit** [comment]
I was looking forward to fixing this but I just noticed if you use double-quotes It works for me.

```
<?php
include('php-riot-api.php');
$summoner_name = "øhm";

$test = new riotapi('euw');
$r = $test->getSummonerByName($summoner_name);

print_r($r);
?>
```

```
Array
(
    [øhm] => Array
        (
            [id] => 38978760
            [name] => øhm
            [profileIconId] => 25
            [summonerLevel] => 4
            [revisionDate] => 1367020055000
        )

)
```

Please confirm this works for you as well so that I can tick this as already working in my eventual fork to-do list.

**Comment by kevinohashi** [comment]
double quotes seems to fix this issue.
