### ISSUE TITLE
Respect Retry-After header

### ISSUE THREAD

**Issue by MasterCassim** [kevinohashi/php-riot-api#34]
Maybe the api could catch RateLimit exceeded errors and look for the response header Retry-After and reissuing the request if some configuration variable is set. The problem is that with multiple users calling the php files the queue for every single user will not hold enough entries to wait querying.

**Comment by kevinohashi** [comment]
Yeah this wasn't written with parallelization in mind. It should definitely be considered, I don't have time to figure it out right now and implement it. Any chance you would be interested in trying to?

**Comment by MasterCassim** [comment]
I have written a solution for myself which does not include the headers but rather uses a database to store all requests and checks against it if there is still space left.

**Comment by kevinohashi** [comment]
I wonder if we could create a solution similar to the new caching scheme for rate limit checking. It would basically be a flatfile database to keep track of this stuff.

**Comment by Supericy** [comment]
Hopefully fixed in: https://github.com/kevinohashi/php-riot-api/pull/46
