### ISSUE TITLE
Riot added current game info

### ISSUE THREAD

**Issue by Virusscript24** [kevinohashi/php-riot-api#38]
https://developer.riotgames.com/discussion/riot-games-api/show/ji66sYEN

They added their current game info api, plz add if you can spare some time

**Comment by MarlonJD** [comment]
I create this function but there are so many way to finish

**Comment by Virusscript24** [comment]
? so it works not or not?

Or is it partly finished?

**Comment by kevinohashi** [comment]
I'll add this when I get a chance

**Comment by didsun** [comment]
Hi, whatsup with update? :)

**Comment by Virusscript24** [comment]
Same here, im running out of other stuff i can do first in my software :(

**Comment by kevinohashi** [comment]
I've been really busy, let me see what I can do this coming week.

**Comment by Virusscript24** [comment]
Would be awesome :)
Sadly i cant do it myself :(

But atually i only need a list of the players and if its 5v5 or not. Everything else isnt high priority

**Comment by gregtampa** [comment]
Stop telling people what to do virus. We will fork it and write when we have time. Otherwise pay me. 
Peace out. This isn't a bug.

**Comment by Virusscript24** [comment]
I didn't want to bug you, I'm sorry :(
Just do it whenever you want or don't do it, I'll deal with it somehow.

**Comment by kevinohashi** [comment]
Ok I added this in, it seemed to work in my limited testing.
https://github.com/kevinohashi/php-riot-api/commit/a965652b97b57f36f9a65c0d9ba5dd3e89a3b58b
