### ISSUE TITLE
Problem...

### ISSUE THREAD

**Issue by Stavros3** [kevinohashi/php-riot-api#39]
Hello. im using the php-riot-api-master package 2 months now and it works perfectly... But.. Now i try to make calls and didnt work.. Then. i try to run the new version and return me this message

"Fatal error: Uncaught exception 'Exception' with message 'NO_RESPONSE' in /home/summoner/public_html/test/php-riot-api.php:307 Stack trace: #0 /home/summoner/public_html/test/php-riot-api.php(219): riotapi->request('https//{region}...') #1 /home/summoner/public_html/test/testing.php(14): riotapi->getSummonerByName('RiotSchmick') #2 {main} thrown in /home/summoner/public_html/test/php-riot-api.php on line 307"
this is the message of testing file. I have add the correct api btw..

**Comment by kevinohashi** [comment]
can you output the full URL it's calling (remove your api key)?

**Comment by Stavros3** [comment]
Well i fix it! the links 
        const API_URL_1_1 = "https://{region}.api.pvp.net/api/lol/{region}/v1.1/";
	const API_URL_1_2 = "https://{region}.api.pvp.net/api/lol/{region}/v1.2/";
	const API_URL_1_3 = "https://{region}.api.pvp.net/api/lol/{region}/v1.3/";
	const API_URL_1_4 = "https://{region}.api.pvp.net/api/lol/{region}/v1.4/";
	const API_URL_2_1 = "https://{region}.api.pvp.net/api/lol/{region}/v2.1/";
	const API_URL_2_2 = "https://{region}.api.pvp.net/api/lol/{region}/v2.2/";
	const API_URL_2_3 = "https://{region}.api.pvp.net/api/lol/{region}/v2.3/";
	const API_URL_2_4 = "https://{region}.api.pvp.net/api/lol/{region}/v2.4/";
	const API_URL_2_5 = "https://{region}.api.pvp.net/api/lol/{region}/v2.5/";
	const API_URL_STATIC_1_2 = 'https://global.api.pvp.net/api/lol/static-data/{region}/v1.2/';

didnt have the  ":" symbol...

**Comment by kevinohashi** [comment]
Doh. I didn't copy+paste because API keys, just did it manually and screwed up. Fixed now in the library.
