### ISSUE TITLE
Caching doesn't work for me

### ISSUE THREAD

**Issue by Virusscript24** [kevinohashi/php-riot-api#41]
I wanted to rebuilt everything from scratch because i've made changes to the desktop application so i just tried the current php file together with the testings.php

Now it says:

> Parse error: syntax error, unexpected '[' in /home/u834577974/public_html/call/FileSystemCache.php on line 69

Is that my fault? did i miss downloading anything etc.?

**Comment by kevinohashi** [comment]
Looks like a PHP 5.4 problem. http://php.net/manual/en/migration54.new-features.php

it's the shortened array syntax. I should probably change that to the traditional one which would allow 5.3 support (which is already required to run this library).

**Comment by kevinohashi** [comment]
try this: https://github.com/kevinohashi/php-riot-api/commit/1040d2a5d879fb93f26d5a2c0cb91b35c141126a should be good to go

**Comment by Virusscript24** [comment]
Works perfectly :) Thx for the fast reply!
