### ISSUE TITLE
How to get $matchId

### ISSUE THREAD

**Issue by pabliito07** [kevinohashi/php-riot-api#44]
Hi, first thanks for the plugin, it help me really a lot. Now i am trying to get info about the current match of a player. I found the function getMatch but i have to write the matchId. My question is.. how i get the matchid?

**Comment by kevinohashi** [comment]
So you need summonerID and then use getCurrentGame($id,$platform). Platform is generally region code with '1' but check api reference. NA1 is what I tested on.
