### ISSUE TITLE
Error Not Found with getMatch & getMatchHistory

### ISSUE THREAD

**Issue by ValentinPierart** [kevinohashi/php-riot-api#47]
Hi !

I just started using your API and tried to test some functions, but I found that getMatch and getMatchHistory give me the error 404 : NOT FOUND : 

	include('riotapi/php-riot-api.php');
	include('riotapi/FileSystemCache.php');

	$summoner = htmlspecialchars($_GET["summoner"]);
	$region = $_GET["region"];

	$api = new riotapi($region);
	$cache = new riotapi($region, new FileSystemCache('cache/'));
	
	$sum_id = null;
	
	try {
		$sum_id = $api->getSummonerId($summoner);
	} catch(Exception $e) {
		echo "Error: " . $e->getMessage();
	}	
	
	$match = $api->getMatchHistory($sum_id);

$sum_id is valid, I can use it with other functions.

Am I doing something wrong ?

Valentin.

**Comment by kevinohashi** [comment]
Try editing php-riot-api and put an echo after it creates the $call variable. What does that say? You can try the raw url in the browser to see what you get too (will need to add api_key=<key> and make sure you replace region.

**Comment by ValentinPierart** [comment]
https://{region}.api.pvp.net/api/lol/{region}/v2.2/matchhistory/35569162

It's works fine in the browser, but not the request :(

**Comment by kevinohashi** [comment]
See that's bizarre because that means the request should be getting created correctly. Try echoing it out $url in request()? I'm kinda puzzled on this one

**Comment by ValentinPierart** [comment]
getSummonerId = https://EUW.api.pvp.net/api/lol/EUW/v1.4/summoner/by-name/samwindu?api_key=524be14d-fe90-42d4-9817-83daca734a1c
This one works.

getMatchHistory = https://EUW.api.pvp.net/api/lol/EUW/v2.2/matchhistory/35569162?api_key=524be14d-fe90-42d4-9817-83daca734a1c
This one don't when the region is in uppercase

**Comment by kevinohashi** [comment]
Try passing everything lowercase. Bizarre behavior from the riot API and I'm definitely able to reproduce that.

**Comment by ValentinPierart** [comment]
Yep, from now on I use the regions on lowercase !

**Comment by kevinohashi** [comment]
Glad we got that figured out :)
