### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'UNAUTHORIZED'

### ISSUE THREAD

**Issue by BasedLord** [kevinohashi/php-riot-api#49]
Hello, I have downloaded your API and attempted to execute testing.php on my xxamp and webserver.
I am continuously getting the following error

Fatal error: Uncaught exception 'Exception' with message 'UNAUTHORIZED' in C:\xampp\htdocs\public_html\riotapi\php-riot-api.php:324 Stack trace: #0 C:\xampp\htdocs\public_html\riotapi\php-riot-api.php(154): riotapi->request('https://{region...') #1 C:\xampp\htdocs\public_html\riotapi\testing.php(23): riotapi->getLeague(585897) #2 {main} thrown in C:\xampp\htdocs\public_html\riotapi\php-riot-api.php on line 324

I feel like this is a simple fix and apologize if so, I am trying to learn.
I have checked my PHP version and API key

**Comment by kevinohashi** [comment]
Can you echo out the URL it's trying to hit? You can put it into a browser and see if that works. Need to figure out if it's malformed for some reason or the apikey is bad. UNAUTHORIZED seems like a bad key somehow, but without more details, it's hard to say.

**Comment by BasedLord** [comment]
Strange, I tried it again this morning and it is working fine :dancer:

**Comment by BasedLord** [comment]
Weird, It is working now that I reuploaded the files to my webserver and on xxamp... Thanks for your time

**Comment by kevinohashi** [comment]
maybe riot's API servers were down or having issues. Glad it's working now.
