### ISSUE TITLE
'getMatchHistory' results in 'Undefined offset'

### ISSUE THREAD

**Issue by StreakyCat** [kevinohashi/php-riot-api#50]
Notice: Undefined offset: 403 in [ ... ] \ php-riot-api.php on line 324

**Comment by kevinohashi** [comment]
ok, so I added the error (403 - Access Denied) to the code. It shouldn't throw that error in the error exception handler now. Your problem seems to be with your credentials though if you're getting that status code.

**Comment by StreakyCat** [comment]
I fixed it by tweaking your script's function "getMatchHistory".
Riot seemed to have changed "matchlist" to "recent", worked for me.

**Comment by twyrostek** [comment]
Hello, I wanted to share how i solved this problem.

on line 100 of php-riot-api.php(134 of github) there is the following line of code:

$call = self::API_URL_2_2  . 'matchhistory/' . $id;

I changed this code to the following:

$call = self::API_URL_2_2  . 'matchlist/by-summoner/' . $id;

after making this change I no longer experience this issue. I think it should be safe to update your api with this new code. It seems that riot must have changed the url in the api.

**Comment by kevinohashi** [comment]
ok ive updated the library with that code, thanks! (in the future, feel free to submit a pull request)
