### ISSUE TITLE
Can't get division from summonerID

### ISSUE THREAD

**Issue by rensknoors** [kevinohashi/php-riot-api#52]
First of all thank you for your great work, it helped me alot.
I'm kind of new to this and have to use an API for a schoolproject but I'm having trouble accessing some data. I already found out how to get summonerID and league tier from the summonername but I can't find out how to get the division.

I hope you have time to help me. If i find out how to get to the division, I'm sure I can find the rest myself.

This is how I tried to get to the division:

$r = $test->getLeague($summID);
$div = $r[$summID][0][0]['division'];
print_r($div);

The second [0] was because the division was inside the first array, not sure if this is the right way

**Comment by JohnCarlo22** [comment]
Are you trying to get the division of the entered summonerId? If you are than you should be doing this:

$r = $test->getLeague($summID, 'entry');
$div = $r[$summID][0]['entries'][0]['division'];
print_r($div);

**Comment by rensknoors** [comment]
Thanks, that's exactly what I needed, I just didn't get the entire 'entry' part.

I guess this thread can be closed now.
