### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by Bdoom** [kevinohashi/php-riot-api#54]
How exactly does the "caching" system work? What is the use of it? How would I use it within my code?

**Comment by Bdoom** [comment]
For eample I have this code:

try {
    $data = $riotCache->getSummonerId($summoner_name);
	$currentGame2 = $riotCache->getCurrentGame($data, "NA1");
	print_r($currentGame2);
} catch(Exception $e) {
    echo "Error: " . $e->getMessage();
};


try {
	$summonerID = $riot->getSummonerId($summoner_name);
	$currentGame = $riot->getCurrentGame($summonerID, "NA1");
	print_r($currentGame);
	
	
} catch(Exception $e) {
    echo "Error: " . $e->getMessage();
};


Does this mean that if I put print_r($currentGame2); it will post the json data that is stored within /cache/ instead of grabbing data from riot again? Won't it be like this:

{"createdAt":1447367558,"ttl":3600,"data":"{\"gusu\":{\"id\":64887680,\"name\":\"GUSU\",\"profileIconId\":750,\"summonerLevel\":30,\"revisionDate\":1447366190000}}"}

That's not the same as regular json data from riot... Like this: 

{"gusu":{"id":64887680,"name":"GUSU","profileIconId":750,"summonerLevel":30,"revisionDate":1447366190000}}

Is there any simple way to transform the cached data into what is above? I want to be able to make my script check the cache before making an ajax request.

**Comment by kevinohashi** [comment]
The caching works by checking to see if it has saved it before and returning data from cache if it has. If it hasn't, it goes out and grabs it like normal and returns that. It also saves that call to cache in case it's requested again.

**Comment by Bdoom** [comment]
So when I use $riot = new riotapi(new filesystemcache) it will check the cache before? I also created a new function and was wondering how to upload it

**Comment by kevinohashi** [comment]
It should. I'm not sure what you mean by created a new function and upload it?

**Comment by Bdoom** [comment]
Oh yeah I created a new function for the api and I was wondering if you could add it to the api. I had to create this function for my site.

**Comment by kevinohashi** [comment]
You're welcome to submit a pull request so it can be reviewed for possible inclusion. What does the function do?

**Comment by Bdoom** [comment]
It just gets the champion By it's ID. getChampion() returns all champion
information while my function "getChampionByID" allows someone to get a
champion based on it's ID. How do I submit a pull request?

**Comment by kevinohashi** [comment]
https://help.github.com/articles/using-pull-requests/

**Comment by Bdoom** [comment]
I just realized that getMatchHistory() seems to be deprecated.  I think riot uses this now:

https://na.api.pvp.net/api/lol/na/v1.3/game/by-summoner/{summoner_id}/recent?api_key={api_key}

**Comment by Bdoom** [comment]
Just found it on the forums: https://developer.riotgames.com/discussion/community-discussion/show/iz34oFti

Yeah they removed it 2 months ago. You should remove it from the project
